/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.hackathon.Hackathon;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appCreateHacakthon() {
        Hackathon app = new Hackathon();

    }
}
